Unified Unix tasks in `cleanup` role

diff --git a/nova/core/roles/cleanup/tasks/unix.yml b/nova/core/roles/cleanup/tasks/unix.yml
--- a/nova/core/roles/cleanup/tasks/unix.yml
+++ b/nova/core/roles/cleanup/tasks/unix.yml
@@ -1,6 +1,5 @@
 ---
-# No systemd (journal) in FreeBSD
-- name: Cleaning up Linux machine...
+- name: Cleaning up Unix machine... # noqa: risky-shell-pipe
   ansible.builtin.shell: |
     {{ 'setenv HISTFILE "/dev/null"' if ansible_facts.system == 'FreeBSD' else 'export HISTFILE=/dev/null' }}
     rm -f /home/*/.ssh/known_hosts
@@ -47,31 +46,31 @@
     rm -f /var/log/upstart/*
     rm -f /var/log/xferlog*
     rm -rf /home/*/.cache/*
-    rm -rf /home/gt/.bash_history
     rm -rf /var/log/installer/*
-    {{ 'service apache2 restart || true' if ansible_facts.distribution | default('') != 'Alpine' else '' }}
-    {{ 'if [ -d "/run/log/journal" ]; then find /run/log/journal -name "*.journal" | xargs rm -f; fi' if ansible_facts.system | default('') != 'FreeBSD' }}
-  args:
-    executable:
-      "/bin/{{  'tcsh' if ansible_facts.system | default('') == 'FreeBSD' else 'sh' if ansible_facts.distribution | default('')
-      == 'Alpine' else 'bash' }}"
+    if command -v apache2 >/dev/null 2>&1; then
+      service apache2 restart || systemctl restart apache2 || /etc/init.d/apache2 restart || apachectl -k graceful || true
+    fi
+    if [ -d "/run/log/journal" ]; then
+      find /run/log/journal -name "*.journal" | xargs rm -f
+    fi
   changed_when: true
 
-- name: Removing Linux shell history...
+- name: Removing Unix shell history...
   ansible.builtin.shell: |
     rm -f /home/*/.*_history
     rm -f /root/.*_history
-  args:
-    executable:
-      "/bin/{{  'tcsh' if ansible_facts.system | default('') == 'FreeBSD' else 'sh' if ansible_facts.distribution | default('')
-      == 'Alpine' else 'bash' }}"
   changed_when: true
   when: cleanup_remove_bash_history
 
 - name: Clearing journalctl...
-  ansible.builtin.command: journalctl --rotate --vacuum-time=1s
+  ansible.builtin.shell: |
+    if command -v journalctl >/dev/null 2>&1; then
+      journalctl --rotate
+      journalctl --vacuum-time=1s
+    else
+      echo "journalctl not found, skipping..."
+    fi
   changed_when: true
-  when: ansible_facts.distribution | default('') != 'Alpine'
 
 - name: Setting reboot_on_finalize to true... # This will reboot the VM during nova.core.finalize role
   ansible.builtin.set_fact:
